// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use serde::{Serialize, Deserialize};
use std::time::SystemTime;

#[derive(Serialize, Deserialize, Queryable, Debug)]
pub struct Todo {
    pub id: i32,
    pub user_id: Option<i32>,
    pub task: String,
    pub is_completed: Option<bool>,
}

#[derive(Serialize, Deserialize, Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub password: String,
    pub created_on: SystemTime,
}

