// this is automaticallyn generated by diesel command
// diset migration generate <Table_name>
table! {
    users (id) {
        id -> Int4,
        username -> Varchar,
        password -> Varchar,
        created_on -> Timestamp,
    }
}
