// this is automaticallyn generated by diesel command
// diset migration generate <Table_name>
table! {
    todos (id) {
        id -> Int4,
        user_id -> Nullable<Int4>,
        task -> Varchar,
        is_completed -> Nullable<Bool>,
    }
}

table! {
    users (id) {
        id -> Int4,
        username -> Varchar,
        password -> Varchar,
        created_on -> Timestamp,
    }
}

joinable!(todos -> users (user_id));

allow_tables_to_appear_in_same_query!(
    todos,
    users,
);
